### ISSUE TITLE
To do for next release with Gammapy v1.3 support

### ISSUE THREAD

**Issue by chaimain** [chaimain/asgardpy#186]
### 🚀 The feature, motivation and pitch

Additions/Modifications -

- [x] Internal [code](https://github.com/chaimain/asgardpy/blob/main/src/asgardpy/analysis/analysis.py#L143-L193) for estimation of EBL-deabsorbed spectra/model
- [x] Maybe fix #175 
- [x] Resolve #170 
- [x] ~~Check for reverting #182~~ For the final version maybe
- [x]  Update to astropy =7 or < 8.0
- [x] Update [lines](https://github.com/chaimain/asgardpy/blob/main/src/asgardpy/data/target.py#L533-L536) in code for `FoVBackgroundModel`
- [x] Check the usage of the new `FitResult` object - Serialization being combined with those of Models
- [x] Create a dedicated documentation page to list the distinct features of asgardpy in comparison to the latest stable release of gammapy
- [x] The default spectral model's index is set at 0. Fix in the test [here](https://github.com/chaimain/asgardpy/blob/main/src/asgardpy/config/tests/test_config.py#L178)
- [x] #187
- [x] #188
- [x] Support python 3.13 and maybe remove 3.11?
- [x] Check the serialisation efforts on each type of Dataset. See example of 3D dataset [here](https://docs.gammapy.org/dev/tutorials/data/fermi_lat.html#serialisation) and maybe try generalizing or including serialisation as `yaml` files as another option. Have to modify code [here](https://github.com/chaimain/asgardpy/blob/main/src/asgardpy/io/io_dl4.py#L93-L141).
- [x] Include the workaround for reading `Models` file created with Gammapy v <1.2 which includes `TemplateSpatialModel` - See [Issue 5549](https://github.com/gammapy/gammapy/issues/5549)
- [x] #195

Removal - 

- [x] Additional dataset of PKS 2155-304 (From #174)
- [x] ~~Additional dataset of LST1 DL4 dataset (From #184)~~ Not included in Gammapy v1.3. For the final version maybe

**Comment by chaimain** [comment]
Compare with the new update on Gammapy HLI from [PR 3852](https://github.com/gammapy/gammapy/pull/3852) to update https://asgardpy.readthedocs.io/en/latest/need_for_asgardpy.html

**Comment by chaimain** [comment]
The workaround required to read `TemplateSpatialModel` objects written with Gammapy <1.2 is not essential to be included in asgardpy, as it only creates such objects with the base Gammapy, and does not read an existing object.

**Comment by chaimain** [comment]
For final version:

- [ ] #195 
- [ ] #196
